// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SangtuariCareerCompass.Data;

#nullable disable

namespace SangtuariCareerCompass.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260910105108_AddPsychologistId")]
    partial class AddPsychologistId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SangtuariCareerCompass.Models.PsychologistUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Degree")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("SilpEndDate")
                        .HasColumnType("date");

                    b.Property<string>("SilpNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("SilpStartDate")
                        .HasColumnType("date");

                    b.Property<string>("StrNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("PsychologistUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 9, 10, 10, 51, 7, 944, DateTimeKind.Utc).AddTicks(6065),
                            Email = "admin@sangtuari.com",
                            FullName = "Kepala Psikolog Sangtuari",
                            IsActive = true,
                            PasswordHash = "$2a$11$OowRFjEibhIi0OO1ySbXauaG46MT4ia9MDMMHENA.x0McGCsLyLG2",
                            Role = "Head"
                        });
                });

            modelBuilder.Entity("SangtuariCareerCompass.Models.UserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("Answers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SubTestName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserAssessmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserAssessmentId");

                    b.ToTable("UserAnswers");
                });

            modelBuilder.Entity("SangtuariCareerCompass.Models.UserAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("AdditionalData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("AssessmentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserAssessments");
                });

            modelBuilder.Entity("SangtuariCareerCompass.Models.UserTestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PsychologistId")
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("ResultDetails")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TestCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserAssessmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserAssessmentId");

                    b.ToTable("UserTestResults");
                });

            modelBuilder.Entity("SangtuariCareerCompass.Models.UserAnswer", b =>
                {
                    b.HasOne("SangtuariCareerCompass.Models.UserAssessment", "UserAssessment")
                        .WithMany()
                        .HasForeignKey("UserAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAssessment");
                });

            modelBuilder.Entity("SangtuariCareerCompass.Models.UserTestResult", b =>
                {
                    b.HasOne("SangtuariCareerCompass.Models.UserAssessment", "UserAssessment")
                        .WithMany()
                        .HasForeignKey("UserAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAssessment");
                });
#pragma warning restore 612, 618
        }
    }
}
