// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SangtuariCareerCompass.Data;

#nullable disable

namespace SangtuariCareerCompass.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260810083842_AddUserTestResultsTable")]
    partial class AddUserTestResultsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SangtuariCareerCompass.Models.UserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("Answers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SubTestName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserAssessmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserAssessmentId");

                    b.ToTable("UserAnswers");
                });

            modelBuilder.Entity("SangtuariCareerCompass.Models.UserAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("AdditionalData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("AssessmentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserAssessments");
                });

            modelBuilder.Entity("SangtuariCareerCompass.Models.UserTestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("ResultDetails")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TestCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserAssessmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserAssessmentId");

                    b.ToTable("UserTestResults");
                });

            modelBuilder.Entity("SangtuariCareerCompass.Models.UserAnswer", b =>
                {
                    b.HasOne("SangtuariCareerCompass.Models.UserAssessment", "UserAssessment")
                        .WithMany()
                        .HasForeignKey("UserAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAssessment");
                });

            modelBuilder.Entity("SangtuariCareerCompass.Models.UserTestResult", b =>
                {
                    b.HasOne("SangtuariCareerCompass.Models.UserAssessment", "UserAssessment")
                        .WithMany()
                        .HasForeignKey("UserAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAssessment");
                });
#pragma warning restore 612, 618
        }
    }
}
